#!/usr/bin/env bash
# curDir=$(cd $(dirname "$0") && pwd)
cd test

echo "\$ python3 ../shdl.py -h"
python3 ../shdl.py -h
echo ""

# doi test
echo "\$ python3 ../shdl.py https://doi.org/10.1109/5.771073 -v"
python3 ../shdl.py https://doi.org/10.1109/5.771073 -v
echo ""
echo "Waiting for next test"
echo ""
sleep 5 # DO NOT DECREASE THE SLEEP TIME

echo "\$ python3 ../shdl.py https://doi.org/10.1109/5.771073 -v --dryrun --autoname -m sci-hub.st"
python3 ../shdl.py https://doi.org/10.1109/5.771073 -v --dryrun --autoname -m sci-hub.st
echo ""
echo "Waiting for next test"
echo ""
sleep 5

echo "\$ python3 ../shdl.py https://doi.org/10.1109/5.771073 -v --dryrun --output testfile --dir sample"
python3 ../shdl.py https://doi.org/10.1109/5.771073 -v --dryrun --output testfile --dir sample
echo ""
echo "Waiting for next test"
echo ""
sleep 5

# arXiv test
echo "\$ python3 ../shdl.py https://arxiv.org/abs/1501.00001 -v"
python3 ../shdl.py https://arxiv.org/abs/1501.00001 -v
echo ""
echo "Waiting for next test"
echo ""
sleep 5

echo "\$ python3 ../shdl.py https://arxiv.org/abs/1501.00001 -v --autoname --dryrun"
python3 ../shdl.py https://arxiv.org/abs/1501.00001 -v --autoname --dryrun
echo ""
echo "Waiting for next test"
echo ""
sleep 5

echo "\$ python3 ../shdl.py https://arxiv.org/abs/1501.00001 -o arxivTest -v --dryrun"
python3 ../shdl.py https://arxiv.org/abs/1501.00001 -o arxivTest -v --dryrun
echo ""
echo "Waiting for next test"
echo ""
sleep 5

echo "\$ mkdir -p sample && python3 ../shdl.py https://arxiv.org/abs/1501.00001 -d sample -o arxivTest -v --dryrun"
mkdir -p sample && python3 ../shdl.py https://arxiv.org/abs/1501.00001 -d sample -o arxivTest -v --dryrun
echo ""

# error test
echo "\$ python3 ../shdl.py https://doi.org/nonexistence/doi"
python3 ../shdl.py https://doi.org/nonexistence/doi
echo ""
echo "Waiting for next test"
echo ""
sleep 5

echo "\$ python3 ../shdl.py https://doi.org/10.1109/5.771073 -p invalidproxy -v"
python3 ../shdl.py https://doi.org/10.1109/5.771073 -p invalidproxy -v
echo ""
echo "Waiting for next test"
echo ""
sleep 5

echo "\$ python3 ../shdl.py https://arxiv.org/nonexistence/doi -v"
python3 ../shdl.py https://arxiv.org/nonexistence/doi -v
echo ""
echo "Waiting for next test"
echo ""
sleep 5

echo "\$ python3 ../shdl.py https://arxiv.org/abs/1501.00001 -p invalidproxy"
python3 ../shdl.py https://arxiv.org/abs/1501.00001 -p invalidproxy
echo ""
echo "Waiting for next test"
echo ""
sleep 5