#!/usr/bin/env bash
# curDir=$(cd $(dirname "$0") && pwd)
cd test

echo "\$ python3 ../shdl.py -h"
python3 ../shdl.py -h
echo ""

echo "\$ python3 ../shdl.py https://doi.org/10.1109/5.771073"
python3 ../shdl.py https://doi.org/10.1109/5.771073
echo ""

echo "\$ python3 ../shdl.py https://doi.org/10.1109/5.771073 -v"
python3 ../shdl.py https://doi.org/10.1109/5.771073 -v
echo ""

echo "\$ python3 ../shdl.py https://doi.org/10.1109/5.771073 -v --autoname"
python3 ../shdl.py https://doi.org/10.1109/5.771073 -v --autoname
echo ""

echo "\$ python3 ../shdl.py https://doi.org/10.1109/5.771073 -o test -v"
python3 ../shdl.py https://doi.org/10.1109/5.771073 -o test -v
echo ""

echo "\$ mkdir -p sample && python3 ../shdl.py https://doi.org/10.1109/5.771073 -d sample -o test -v"
mkdir -p sample && python3 ../shdl.py https://doi.org/10.1109/5.771073 -d sample -o test -v
echo ""

echo "\$ python3 ../shdl.py https://arxiv.org/abs/1501.00001 -v"
python3 ../shdl.py https://arxiv.org/abs/1501.00001 -v
echo ""

echo "\$ python3 ../shdl.py https://arxiv.org/abs/1501.00001 -v --autoname"
python3 ../shdl.py https://arxiv.org/abs/1501.00001 -v --autoname
echo ""

echo "\$ python3 ../shdl.py https://arxiv.org/abs/1501.00001 -o arxivTest -v"
python3 ../shdl.py https://arxiv.org/abs/1501.00001 -o arxivTest -v
echo ""

echo "\$ mkdir -p sample && python3 ../shdl.py https://doi.org/10.1109/5.771073 -d sample -o arxivTest -v"
mkdir -p sample && python3 ../shdl.py https://doi.org/10.1109/5.771073 -d sample -o arxivTest -v
echo ""

# error test
echo "\$ python3 ../shdl.py https://doi.org/foo"
python3 ../shdl.py https://doi.org/foo
echo ""

echo "\$ python3 ../shdl.py https://doi.org/10.1109/5.771073 -p bar"
python3 ../shdl.py https://doi.org/10.1109/5.771073 -p bar
echo ""

echo "\$ python3 ../shdl.py https://doi.org/10.1109/5.771073 -v -p bar"
python3 ../shdl.py https://doi.org/10.1109/5.771073 -v -p bar
echo ""

echo "\$ python3 ../shdl.py https://arxiv.org/foo"
python3 ../shdl.py https://arxiv.org/foo
echo ""

echo "\$ python3 ../shdl.py https://arxiv.org/abs/1501.00001 -p bar"
python3 ../shdl.py https://arxiv.org/abs/1501.00001 -p bar
echo ""

echo "\$ python3 ../shdl.py https://arxiv.org/abs/1501.00001 -v -p bar"
python3 ../shdl.py https://arxiv.org/abs/1501.00001 -v -p bar
echo ""